# Generated by Django 3.2.9 on 2021-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apihero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(related_name='company', to='apihero.Company'),
        ),
    ]
